### ISSUE TITLE
Image upload error

### ISSUE THREAD

**Issue by clementsan** [cytomine/Cytomine-bootstrap#35]
Hi, 

I installed Cytomine-bootstrap v3.0.1 on a linux work desktop (OpenSuse Leap 42.2), as a local installation to try and test Cytomine. I followed the default instructions available here: 
[https://documentation.cytomine.org/admin-guide/install#install-2] (https://documentation.cytomine.org/admin-guide/install#install-2)
 I used the default configuration file, created folders referenced in `PATH...` configuration keys, and appended the `/etc/hosts/` file. 
Config file snippet:
```
#URLs
CORE_URL=localhost-core
IMS_URL1=localhost-ims
IMS_URL2=localhost-ims2
UPLOAD_URL=localhost-upload
...
#Paths
IMS_STORAGE_PATH=/data/images
IMS_BUFFER_PATH=/data/images/_buffer
BACKUP_PATH=/data/backup
ALGO_PATH=/data/algo/
```
Host file snippet:
```
127.0.0.1         localhost-core
127.0.0.1         localhost-ims
127.0.0.1         localhost-ims2
127.0.0.1         localhost-upload
127.0.0.1         rabbitmq
```

While Cytomine installed successfully, I cannot upload any images, as an admin or simple user. The UI displays an "upload error", and the IMS log file shows some connection timeout issues (please see error below). Not having direct expertise in this, do you have any insights on how to solve it? Are there any additional configurations needed? I don't know if this is a standard issue users may face for a local installation. 

IMS log file snippet:
```
2021-07-19T18:54:46.796398873Z 2021-07-19 18:54:45,850 [quartzScheduler_Worker-7] ERROR listeners.ExceptionPrinterJobListener  - Exception occurred in job: Grails Job
2021-07-19T18:54:46.796408040Z org.quartz.JobExecutionException: 0 Connect to localhost-core:80 [localhost-core/172.17.0.1] failed: Connection timed out (Connection timed out) [See nested exception: 0 Connect to localhost-core:80 [localhost-core/172.17.0.1] failed: Connection timed out (Connection timed out)]
2021-07-19T18:54:46.796417704Z 	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
2021-07-19T18:54:46.796426388Z 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2021-07-19T18:54:46.796434815Z 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2021-07-19T18:54:46.796443349Z Caused by: 0 Connect to localhost-core:80 [localhost-core/172.17.0.1] failed: Connection timed out (Connection timed out)
2021-07-19T18:54:46.796451990Z 	at be.cytomine.client.Cytomine.fetchCollection(Cytomine.java:304)
2021-07-19T18:54:46.796467812Z 	at be.cytomine.client.Cytomine.getDeleteCommandByDomainAndAfterDate(Cytomine.java:1704)
2021-07-19T18:54:46.796477332Z 	at ims.DeleteImageFileJob.execute(DeleteImageFileJob.groovy:35)
2021-07-19T18:54:46.796486016Z 	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
2021-07-19T18:54:46.796494571Z 	... 2 more
2021-07-19T18:54:46.796503961Z Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost-core:80 [localhost-core/172.17.0.1] failed: Connection timed out (Connection timed out)
2021-07-19T18:54:46.796513258Z 	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
2021-07-19T18:54:46.796522020Z 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
2021-07-19T18:54:46.796530754Z 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
2021-07-19T18:54:46.796541547Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
2021-07-19T18:54:46.796550321Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
2021-07-19T18:54:46.796558929Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
2021-07-19T18:54:46.796567593Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
2021-07-19T18:54:46.796576236Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
2021-07-19T18:54:46.796584866Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
2021-07-19T18:54:46.796593518Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
2021-07-19T18:54:46.796602232Z 	at be.cytomine.client.HttpClient.get(HttpClient.java:140)
2021-07-19T18:54:46.796610673Z 	at be.cytomine.client.Cytomine.fetchCollection(Cytomine.java:289)
2021-07-19T18:54:46.796619264Z 	... 5 more
2021-07-19T18:54:46.796627655Z Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
2021-07-19T18:54:46.796636297Z 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2021-07-19T18:54:46.796644883Z 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2021-07-19T18:54:46.796653565Z 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2021-07-19T18:54:46.796662124Z 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2021-07-19T18:54:46.796670700Z 	at java.net.Socket.connect(Socket.java:589)
2021-07-19T18:54:46.796679223Z 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
2021-07-19T18:54:46.796688003Z 	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
2021-07-19T18:54:46.796696815Z 	... 16 more
```

Thanks!

**Comment by loic911** [comment]
I'm closing it as it seems to be resolved (https://forum.image.sc/t/error-uploading-image-into-cytomine/28746/9)
