### ISSUE TITLE
software_router deployment error

### ISSUE THREAD

**Issue by trevordo** [cytomine/Cytomine-bootstrap#4]
Hi,

I've been trying to install Cytomine on Ubunutu 14.04 and 16.04 on AWS ec2.  I am able to deploy and everything seems fine; logging in and viewing projects.  However when I try to run analysis jobs, the jobs show a status of "not launched." 

Reviewing my docker logs everything seems fine except for software_router.  I see this.

```
ubuntu@ip-172-31-38-191:~$ sudo docker logs software_router
********************************************************************
Launch :
Softwares :software collection
ComputeTermArea added
TissueDetect added
TissueSegment added
CellClassifier added
LandMark added
Export LandMark added
DONE
Softwares :software collection
********************************************************************
ln: failed to create symbolic link ‘/sys/fs/cgroup/systemd/name=systemd’: Operation not permitted
Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
time="2017-08-07T20:16:13.729782515Z" level=info msg="libcontainerd: new containerd process, pid: 164"
Exception in thread "main" java.lang.NoClassDefFoundError: [Ljava/util/HashMap$Entry;
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.codehaus.groovy.reflection.CachedClass$3$1.run(CachedClass.java:84)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:81)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:79)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.CachedClass.getMethods(CachedClass.java:250)
        at groovy.lang.MetaClassImpl.populateMethods(MetaClassImpl.java:334)
        at groovy.lang.MetaClassImpl.fillMethodIndex(MetaClassImpl.java:284)
        at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:2904)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:166)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:182)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:227)
        at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:751)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:71)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at groovy.util.ConfigSlurper.parse(ConfigSlurper.groovy:160)
        at groovy.util.ConfigSlurper$parse$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
        at groovy.util.ConfigSlurper.parse(ConfigSlurper.groovy:148)
        at groovy.util.ConfigSlurper$parse.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at src.be.cytomine.software.consumer.RabbitWorker.<clinit>(RabbitWorker.groovy:30)
Caused by: java.lang.ClassNotFoundException: java.util.HashMap$Entry
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 32 more
time="2017-08-07T20:16:14.734840188Z" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /var/lib/docker/tmp-old: no such file or directory. Deleting synchronously"
time="2017-08-07T20:16:14.748231435Z" level=error msg="AUFS is not supported over aufs"
time="2017-08-07T20:16:14.749612544Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
time="2017-08-07T20:16:14.750682505Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
time="2017-08-07T20:16:14.755012462Z" level=error msg="devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a more recent version of libdevmapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options"
time="2017-08-07T20:16:14.797649063Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-08-07T20:16:14.797911174Z" level=warning msg="Your kernel does not support cgroup rt period"
time="2017-08-07T20:16:14.797928924Z" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2017-08-07T20:16:14.798222515Z" level=info msg="Loading containers: start."
time="2017-08-07T20:16:14.800467547Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-1022-aws/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-1022-aws/modules.dep.bin'\n, error: exit status 1"
time="2017-08-07T20:16:14.801527617Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-1022-aws/modules.dep.bin'`, error: exit status 1"
time="2017-08-07T20:16:14.802691659Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-1022-aws/modules.dep.bin'`, error: exit status 1"
time="2017-08-07T20:16:14.897117926Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2017-08-07T20:16:14.935808147Z" level=info msg="Loading containers: done."
time="2017-08-07T20:16:14.988209942Z" level=info msg="Daemon has completed initialization"
time="2017-08-07T20:16:14.988241418Z" level=info msg="Docker daemon" commit=02c1d87 graphdriver=vfs version=17.06.0-ce
time="2017-08-07T20:16:14.996223564Z" level=info msg="API listen on /var/run/docker.sock"
```
If this error is related to job's not launching, I hope there's a fix.  

Thanks!
Trev

**Comment by geektortoise** [comment]
Hello !
It was an issue with groovy code compiled on java7 and run on java8.
I updated the images on the Dockerhub.
Can you test again ?

Maybe you will need to pull the "cytomine/software_router" docker image from DockerHub before launching the restart_keep ... script.

**Comment by trevordo** [comment]
Perfect! that worked and the installation was successful with no errors. 

Some note my environment is aws ubuntu 16.04.  I had to unmount aufs and remove it, since kernel 4.x no longer requires it.

Thanks!
